[build]
# Netlify will now publish from the 'build' subdirectory
publish = "build"

# This command will:
# 1. Remove the 'build' directory if it exists (rm -rf build)
# 2. Create a fresh 'build' directory (mkdir -p build)
# 3. Copy index.html into the build directory
# 4. Create a template for api-config.js
# 5. Use envsubst to replace the variable in the template and output to api-config.js
# ABSOLUTELY CORRECTED: Removed all problematic backslashes from the TOML command string
command = """
rm -rf build && mkdir -p build && cp index.html build/index.html && \
echo 'window.NETLIFY_API_KEY = "$GOOGLE_API_KEY";' > build/api-config-template.js && \
envsubst '$GOOGLE_API_KEY' < build/api-config-template.js > build/api-config.js && \
rm build/api-config-template.js
"""

# This section ensures the GOOGLE_API_KEY environment variable is available to the build command
[context.production.environment]
GOOGLE_API_KEY = "$GOOGLE_API_KEY"
